#pragma once
#ifndef ANGKASA1_SANDBOX_SANDBOX_APP_DEFINITIONS_H
#define ANGKASA1_SANDBOX_SANDBOX_APP_DEFINITIONS_H

namespace sandbox
{
#define SANDBOX_MAX_MATERIAL_TYPE_IN_DEFINITION 8
}

#endif // !ANGKASA1_SANDBOX_SANDBOX_APP_DEFINITIONS_H
