#pragma once
#ifndef LEARNVK_RENDERER_API_DEFINITIONS_H
#define LEARNVK_RENDERER_API_DEFINITIONS_H

#define MAX_SWAPCHAIN_IMAGE_ALLOWED		3
#define MAX_FRAMES_IN_FLIGHT			2

#endif // !LEARNVK_RENDERER_API_DEFINITIONS_H