#pragma once
#ifndef LEARNVK_RENDERER_API_DEFINITIONS_H
#define LEARNVK_RENDERER_API_DEFINITIONS_H

#include "Library/Memory/Memory.h"

#define MAX_SWAPCHAIN_IMAGE_ALLOWED			3
#define MAX_FRAMES_IN_FLIGHT				2
#define MAX_VERTEX_INPUT_BINDING			8
#define MAX_PIPELINE_DESCRIPTOR_LAYOUT		16
#define MAX_DESCRIPTOR_POOL_TYPE_SIZE		16
#define MAX_DESCRIPTOR_SET_LAYOUT_BINDINGS	16
#define MAX_SHADER_ATTRIBUTES				32
#define MAX_DESCRIPTOR_BINDING_UPDATES		1000
#define MAX_STAGING_BUFFER_SIZE				MEGABYTES(64)

#endif // !LEARNVK_RENDERER_API_DEFINITIONS_H